config/routes.rb
Rails.application.routes.draw do

  root to: "products#index_Top_page"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'register_choice', to: 'users/registrations#register_choice'
  end  

  resources :users, only: :index do
    collection do
      get "logout", to: "users#logout"
    end
  end

  resources :products do
    resources :likes, only: [:create, :destroy, :show]
    resource :comments, only: :create
    resources :searches,only:[:index]
    collection do
      get "index_Top_page"
      get "index_all"
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end

    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  resources :credit_cards, only: [:new, :show, :create, :index, :destroy] do
  end

end

app/models/product.rb
class Product < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many   :images,      dependent: :destroy
  belongs_to :brand, optional: true
  belongs_to :category
  has_one    :purchase, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :like_users, through: :likes, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  

  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank
  
  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%")
  end
  
  # バリデーション
  validates :images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :detail, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :condition, presence: true
  validates :prefecture_id, presence: true          #prefecture_id 配送元
  validates :delivery, presence: true      #発送までの日数 stringに変更
  validates :fee_payer, presence: true     #配送料の負担
  

end

app/controllers/products/searches_controller.rb
class Products::SearchesController < ApplicationController
  before_action :set_ransack

  def index
    @parents = Category.all.order("id ASC").limit(13)
    @products = Product.search(params[:search]).limit(132)
    @search = params[:search]
  end

  private


  def set_ransack
    @q = Product.ransack(params[:q])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :parents_category, only: [:index_Top_page, :index_all, :show, :search, :detail_search]
  before_action :set_product, only: [:show, :destroy,:edit,:update]
  before_action :set_products_all, only: [:index_all, :index_Top_page]
  before_action :set_ransack 
  before_action :ensure_currect_user,only: [:edit,:update,:destroy]

  def index_Top_page
  end

  def index_all
  end

  def new 
    if user_signed_in?
      @product=Product.new
      @product.images.build
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    else
      redirect_to user_session_path
    end
  end

  def create
    @product = Product.new(product_params)
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find((@product).category_id)
    grandchild_category = @product.category
    child_category = grandchild_category.parent
    # 親カテゴリーの配列を取得する
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    # 子カテゴリーの配列を取得する
    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end
    # 孫カテゴリーの配列を取得する
    @category_grandchildren_array = []
    Category.where(ancestry: @category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    if @product.update(product_params)
      redirect_to root_path
    else
      redirect_to edit_product_path(@product)
    end
  end

  def show
    # 商品詳細に関するコントローラー
    @image = @product.images.all
    # コメントに関するコントローラー
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    @comment = @product.comments.build
    @category = Category.find((@product).category_id)
  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
     #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render product_path(params[:id])
    end
  end

  def search
    @products = Product.search(params[:keyword]).order("created_at DESC").limit(25)
  end

  def detail_search
    @search = Product.ransack(params[:q]) 
    @products = @search.result
    render action: :search
  end

  private

  def product_params
    params.require(:product).permit( :name, :detail, :price, :category_id, :brand_id, :condition, :prefecture_id, :fee_payer, :delivery, images_attributes: [:images,:id,:_destroy]).merge(user_id: current_user.id)
  end

  def parents_category
    @parents = Category.order("id ASC").limit(13)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_products_all
    @products = Product.includes(:user, :images, :purchase, :category,).order("created_at DESC")
  end

  def ensure_currect_user
    @product = Product.find_by(id: params[:id])
    if @product.user_id != current_user.id
       redirect_to root_path
    end
  end

  def set_ransack
    @q = Product.ransack(params[:q])
  end

end

app/helpers/products/searches_helper.rb
module Products::SearchesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index_Top_page/_characteristic.html.haml
.characteristic
  .title
    .title__sentence
      FURIMAの特徴
  
  %ul.contents
    %li.content
      .content__image
        = image_tag "material/icon/icon-01.png", alt: "売り買いをする様子のイラスト", width: "210"
      .content__title
        簡単に売り買いできる
      .content__detail
        スマホひとつで、いつでもどこでも簡単に
        %br
        出品・購入が可能！

    %li.content
      .content__image
        = image_tag "material/icon/icon-03.png", alt: "振込をする様子のイラスト", width: "210"
      .content__title
        売上金は即日振込みに対応
      .content__detail
        午前9時までに振込を依頼いただければ、
        %br
        翌日に指定の口座に入金いたします!

    %li.content
      .content__image
        = image_tag "material/icon/icon-04.png", alt: "支払い方法のイラスト", width: "210"
      .content__title
        様々な支払いに対応
      .content__detail
        お支払いは、クレジットカードだけでなく、
        %br
        ポイントや売上金など多彩な方法があります。

app/views/products/index_Top_page/_main-title.html.haml
.main-title
  .content
    .content__caption
      人生を変えるフリマアプリ
    .content__catch-copy
      %ul
        %li.content__catch-copy__sentence
          FURIMAは誰でも簡単に出品・購入できる
        %li.content__catch-copy__sentence
          フリマアプリです。
    .link-logos
      %ul.link-logo
        %li.link-logo__app-store
          = link_to image_tag('material/icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', alt: "appleStore-icon", class: 'appleStore-logo-icon', width: 180), ""
        %li.link-logo__google-play
          = link_to image_tag('material/icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', alt: "googleApp-icon", class: 'googleApp-logo-icon', width: 180), ""

app/views/products/index_Top_page/_middle-links.html.haml
.middle-links
  .content
    .content__caption
      会員数日本１位
    .content__catch-copy__sentence
      FURIMAは、フリマアプリで最も人気。
      %br
      出品・購入回数も業界最多です！
      %br
      ほしかったあの商品に出会えるかもしれません。
    .link-logos
      %ul.link-logo
        %li.link-logo__app-store
          = link_to image_tag('material/icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', alt: "appleStore-icon", class: 'appleStore-logo-icon', width: 180), ""
        %li.link-logo__google-play
          = link_to image_tag('material/icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', alt: "googleApp-icon", class: 'googleApp-logo-icon', width: 180), ""

app/views/products/index_Top_page/_pick-up-brand.html.haml
.pick-up-brand
  .pick-up__title
    ピックアップブランド
  .pick-up__box
    .pick-up__box__title
      =link_to "アーカイバ", "", class: "pick-up_brand_title"
    %ul.productlists
      = link_to "", class: "product" do
        %li.product
          .product__image
            =image_tag "material/icon/product_exam.png", alt: "product"
          .detail
            .product__content
              .product__name
                product3
              .product__price
                30000円
                .product__price__tax
                  (税抜)
            .product__evaluation
              .product__evaluation__star-img
                %i.fas.fa-star
              .product__evaluation__score
                ０
      = link_to "", class: "product" do
        %li.product
          .product__image
            =image_tag "material/icon/product_exam.png", alt: "product"
          .detail
            .product__content
              .product__name
                product2
              .product__price
                20000円
                .product__price__tax
                  (税抜)
            .product__evaluation
              .product__evaluation__star-img
                %i.fas.fa-star
              .product__evaluation__score
                ０
      = link_to "", class: "product" do
        %li.product
          .product__image
            =image_tag "material/icon/product_exam.png", alt: "product"
          .detail
            .product__content
              .product__name
                product1
              .product__price
                10000円
                .product__price__tax
                  (税抜)
            .product__evaluation
              .product__evaluation__star-img
                %i.fas.fa-star
              .product__evaluation__score
                ０

app/views/products/index_Top_page/_pick-up-category.html.haml
.pick-up-category
  .pick-up__title
    ピックアップカテゴリー
  .pick-up__box
    .pick-up__box__title
      =link_to "新規投稿商品", index_all_products_path, class: "pick-up_category_title"
    %ul.productlists
      = render partial: 'products/shared/product', collection: @products.first(3)

app/views/products/index_Top_page/_top-introduction.html.haml
.top-introduction
  .title
    .title__sentence
      FURIMAが選ばれる３つの理由
  %ul.contents
    %li.content
      .content__image
        = image_tag "material/pict/pict-reason-01.jpg", alt: "出品の様子", width: "300"
        .content__number
          1
      .content__title
        %span.enphasis-phrase
          3分
        ですぐに出品
      .content__detail
        スマホで入力するだけで
        %br
        簡単に出品できる！

    %li.content
      .content__image
        = image_tag "material/pict/pict-reason-02.jpg", alt: "使用時の様子", width: "300"
        .content__number
          2
      .content__title
        %span.enphasis-phrase
          シンプル
        で使いやすい
      .content__detail
        めんどくさい入力は必要なく、
        %br
        検索も購入もスムーズ！

    %li.content
      .content__image
        = image_tag "material/pict/pict-reason-03.jpg", alt: "手数料確認の様子", width: "300"
        .content__number
          3
      .content__title
        手数料
        %span.enphasis-phrase
          業界最安値
      .content__detail
        最大3%でお得に出品&購入！