config/routes.rb
Rails.application.routes.draw do

  root to: "products#index_Top_page"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'register_choice', to: 'users/registrations#register_choice'
  end  

  resources :users, only: :index do
    collection do
      get "logout", to: "users#logout"
    end
  end

  resources :products do
    resources :likes, only: [:create, :destroy, :show]
    resource :comments, only: :create
    resources :searches,only:[:index]
    collection do
      get "index_Top_page"
      get "index_all"
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end

    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  resources :credit_cards, only: [:new, :show, :create, :index, :destroy] do
  end

end

app/controllers/products/searches_controller.rb
class Products::SearchesController < ApplicationController
  before_action :set_ransack

  def index
    @parents = Category.all.order("id ASC").limit(13)
    @products = Product.search(params[:search]).limit(132)
    @search = params[:search]
  end

  private


  def set_ransack
    @q = Product.ransack(params[:q])
  end

end

app/helpers/products/searches_helper.rb
module Products::SearchesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form-bar.html.haml
.search-left
  .detail_search
  = search_form_for(@q,url: searches_path) do |f|
    .detail_search_sort
      = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { onchange: 'this.form.submit()'} )
    .detail_search_form
      .detail_search__title
        %h3 詳細検索
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p キーワードを追加する
        = f.search_field :name_cont, placeholder: "例）値下げ"
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p 価格
        .detail_search__group--forms
          = f.search_field :price_gteq, placeholder: "¥ Min"
          %p 〜
          = f.search_field :price_lteq, placeholder: "¥ Max"
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p 商品の状態
        .detail_search__group--check
          = f.select :condition, [["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れ無し","目立った傷や汚れ無し"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], { include_blank: "選択して下さい"}, { class: 'detail_search__group--check', required: true}
            
          .detail_search__btns
            .detail_search__btn--grey
              = link_to "クリア", "/searches",type: "button"
            = f.submit "完了"

      .search-main
  .search-main__result
    - if @items.length > 0
      #{params[:keyword]}の検索結果
      %br #{@items.length}件の商品が見つかりました
    - else
      #{params[:keyword]}の検索結果
      %br 該当する商品がありません。キーワードをかえて検索してください
  - @items.each do |i|
    .search-main__item
      .search-main__item__image
        = link_to item_path(i.id) do
          = image_tag asset_path("#{i.images.first.src}")

      .search-main__item__name
        = i.name
      .search-main__item__price
        ¥ #{i.price}
      -if i.buyer_id.present?
        .sold-icon
          .sold-icon__inner
            SOLD

app/views/searches/_index.html.haml
= render 'products/shared/header'
= render "products/shared/exhibition-btn"
.search-main
  .search-main__result
    - if @products.length > 0
      #{params[:search]}の検索結果
      %br #{@products.length}件の商品が見つかりました
    - else
      #{params[:search]}の検索結果
      %br 該当する商品がありません。キーワードをかえて検索してください
  - @products.each do |i|
    .search-main__product
      .search-main__product__image
        = link_to product_path(i.id) do
          = image_tag asset_path("#{i.images.first.src}")

  
.search-left
  .detail_search
  = search_form_for(@q,url: searches_path) do |f|
    .detail_search_sort
      = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { onchange: 'this.form.submit()'} )
    .detail_search_form
      .detail_search__title
        %h3 詳細検索
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p キーワードを追加する
        = f.search_field :name_cont, placeholder: "例）値下げ"
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p 価格
        .detail_search__group--forms
          = f.search_field :price_gteq, placeholder: "¥ Min"
          %p 〜
          = f.search_field :price_lteq, placeholder: "¥ Max"
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p 商品の状態
        .detail_search__group--check
          = f.select :condition, [["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れ無し","目立った傷や汚れ無し"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], { include_blank: "選択して下さい"}, { class: 'detail_search__group--check', required: true}
            
          .detail_search__btns
            .detail_search__btn--grey
              = link_to "クリア", "/searches",type: "button"
            = f.submit "完了"

= render "products/shared/footer"

app/views/searches/_search.html.haml
= render 'products/shared/header'
= render "products/shared/exhibition-btn"
.search
  .search-container
    .search-left
      .detail_search
  = search_form_for(@q,url: searches_path) do |f|
    .detail_search_sort
      = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { onchange: 'this.form.submit()'} )
    .detail_search_form
      .detail_search__title
        %h3 詳細検索
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p キーワードを追加する
        = f.search_field :name_cont, placeholder: "例）値下げ"
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p 価格
        .detail_search__group--forms
          = f.search_field :price_gteq, placeholder: "¥ Min"
          %p 〜
          = f.search_field :price_lteq, placeholder: "¥ Max"
      .detail_search__group
        .detail_search__group--label
          = fa_icon "search"
          %p 商品の状態
        .detail_search__group--checkbox
          %label
             
            = 'すべて'
        .detail_search__group--checkbox
          %label
            
            = '新品、未使用'
        .detail_search__group--checkbox
          %label
            
            = '未使用に近い'
      .detail_search__btns
        .detail_search__btn--grey
          = link_to "クリア", "/searches",type: "button"
        = f.submit "完了"
    .search-right
      %section.items-box-container
        -if @search.present?
          %h2.search-result-head
            =@search
            %span.search-result-head-text
              の検索結果
          .search-result-number
            ="1-#{@products.count}件表示"
        -else
          %h2.search-result-nil
            検索結果
          .search-result-number
            ="1-#{@products.count}件表示"
        .items-box-content
          
= render "products/shared/footer"

app/views/searches/detail_search.html.haml
= render 'shared/header'
= render 'shared/exhibition-btn'
.search
  .search-container
    .search-left
      = render 'shared/index'
    .search-right
      %section.items-box-container
        -if @search.present?
          %h2.search-result-head
            =@search
            %span.search-result-head-text
              の検索結果
          .search-result-number
            ="1-#{@products.count}件表示"
        -else
          %h2.search-result-nil
            検索結果
          .search-result-number
            ="1-#{@products.count}件表示"
        .items-box-content
          = render @products
= render 'shared/footer'