config/routes.rb
Rails.application.routes.draw do

  root to: "products#index_Top_page"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'register_choice', to: 'users/registrations#register_choice'
  end  

  resources :users, only: :index do
    collection do
      get "logout", to: "users#logout"
    end
  end

  resources :products do
    resources :likes, only: [:create, :destroy, :show]
    resource :comments, only: :create
    resources :searches,only:[:index]
    collection do
      get "index_Top_page"
      get "index_all"
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end

    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  resources :credit_cards, only: [:new, :show, :create, :index, :destroy] do
  end

end

app/models/product.rb
class Product < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many   :images,      dependent: :destroy
  belongs_to :brand, optional: true
  belongs_to :category
  has_one    :purchase, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :like_users, through: :likes, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  

  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank
  
  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%")
  end
  
  # バリデーション
  validates :images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :detail, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :condition, presence: true
  validates :prefecture_id, presence: true          #prefecture_id 配送元
  validates :delivery, presence: true      #発送までの日数 stringに変更
  validates :fee_payer, presence: true     #配送料の負担
  

end

app/controllers/products/searches_controller.rb
class Products::SearchesController < ApplicationController
  before_action :set_ransack

  def index
    @parents = Category.all.order("id ASC").limit(13)
    @products = Product.search(params[:search]).limit(132)
    @search = params[:search]
  end

  private


  def set_ransack
    @q = Product.ransack(params[:q])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :parents_category, only: [:index_Top_page, :index_all, :show, :search, :detail_search]
  before_action :set_product, only: [:show, :destroy,:edit,:update]
  before_action :set_products_all, only: [:index_all, :index_Top_page]
  before_action :set_ransack 
  before_action :ensure_currect_user,only: [:edit,:update,:destroy]

  def index_Top_page
  end

  def index_all
  end

  def new 
    if user_signed_in?
      @product=Product.new
      @product.images.build
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    else
      redirect_to user_session_path
    end
  end

  def create
    @product = Product.new(product_params)
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find((@product).category_id)
    grandchild_category = @product.category
    child_category = grandchild_category.parent
    # 親カテゴリーの配列を取得する
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    # 子カテゴリーの配列を取得する
    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end
    # 孫カテゴリーの配列を取得する
    @category_grandchildren_array = []
    Category.where(ancestry: @category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    if @product.update(product_params)
      redirect_to root_path
    else
      redirect_to edit_product_path(@product)
    end
  end

  def show
    # 商品詳細に関するコントローラー
    @image = @product.images.all
    # コメントに関するコントローラー
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    @comment = @product.comments.build
    @category = Category.find((@product).category_id)
  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
     #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render product_path(params[:id])
    end
  end

  def search
    @products = Product.search(params[:keyword]).order("created_at DESC").limit(25)
  end

  def detail_search
    @search = Product.ransack(params[:q]) 
    @products = @search.result
    render action: :search
  end

  private

  def product_params
    params.require(:product).permit( :name, :detail, :price, :category_id, :brand_id, :condition, :prefecture_id, :fee_payer, :delivery, images_attributes: [:images,:id,:_destroy]).merge(user_id: current_user.id)
  end

  def parents_category
    @parents = Category.order("id ASC").limit(13)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_products_all
    @products = Product.includes(:user, :images, :purchase, :category,).order("created_at DESC")
  end

  def ensure_currect_user
    @product = Product.find_by(id: params[:id])
    if @product.user_id != current_user.id
       redirect_to root_path
    end
  end

  def set_ransack
    @q = Product.ransack(params[:q])
  end

end

app/helpers/products/searches_helper.rb
module Products::SearchesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_footer.html.haml
// frm_appのヘッダー部分のマークアップ
%footer
  .image__area
    .image__area--text
      %span.introduce だれでもかんたん、人生を変えるフリマアプリ
      %br
        今すぐ無料ダウンロード！
    .image__area--link
      =link_to image_tag('material/logo/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', size: "190x60", class: "image__area--link-apple")
      =link_to image_tag('material/logo/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', size: '190x60', class: "image__area--link-google")
  .information__area 
    .information__area--contents
      .information__area--content
        %p.content
          FURIMAについて
        %ul.content-list
          %li.list
            = link_to "会社概要(運営会社)", '#' 
          %li.list
            = link_to "プライバシーポリシー", '#' 
          %li.list 
            = link_to "利用規約", '#'      
          %li.list
            = link_to "ポイントに関する特約", '#'
        
      .information__area--content
        %p.content
          FURIMAを見る
        %ul.content-list
          %li.list 
            = link_to "カテゴリー一覧", '#'
          %li.list
            = link_to "ブランド一覧", '#'

      .information__area--content
        %p.content
          ヘルプ＆ガイド
        %ul.content-list
          %li.list
            = link_to "FURIMAガイド", '#'
          %li.list
            =link_to "FURIMAロゴ利用ガイドライン", '#'
          %li.list 
            = link_to "お知らせ", '#'
    .footer__logo
      =link_to image_tag('material/logo/logo-white.png', alt: "logo", class: "footer__logo--frima", height: "50", width: "150")
      %br 
        .copy-write ©️FURIMA

app/views/products/edit.html.haml
.sign_up
  = render partial:"devise/header" 
  - breadcrumb :edit_product
  = breadcrumbs pretext: "",separator: " &rsaquo; " 
  %main.shipping_main
    %section.shipping_main-container
      .goods_main-inner
        .goods_main-header
          %h2.goods_main-header-text
            商品の情報を入力
        = form_with model: @product,local: true do|f|
          .goods_info
            %section.l-shipping_goods_info
            .goods_form

              .goods_form-image.clearfix
                %h2.goods_form_image-title
                  %h2.label 出品画像
                  %span.must_check 必須
                %br
                %p.goods_form-image-text 最大１０枚までアップロードできます
                .about
                  .box
                    .inner
                      .edit_field#js_field
                        - @product.images.each_with_index do |img, num|
                          =f.check_box :_destroy, class:"hidden_destroy destroy_btn-check",name:"product[images_attributes][#{num}][_destroy]", data:{id:num}
                          =f.hidden_field :id, value: img.id, name:"product[images_attributes][#{num}][id]"
                          .margin_img{id:"margin_#{num}"}
                            .nest_img
                              =image_tag img.images.url,class:"img img_edit",id:"preview_#{num}"
                              .edit_image_btn
                                .destroy_btn{data:{id:num}} 削除
                                .edit_btn{id:"#{num}"}
                                  =f.file_field :images,class: "image_edit-field",accept:"image/*",id:"image_#{num}",name:"product[images_attributes][#{num}][images]",data:{id:num}
                                  =f.hidden_field :id, value: img.id, name:"product[images_attributes][#{num}][id]"
                                  %p.image_edit-text 編集


              .goods_form-explain.clearfix
                %h2.label 商品名
                %span.must_check 必須
                .goods_form-explain-title
                  =f.text_field :name, placeholder:"商品名（必須40文字まで)",class:"goods_form-explain-field", required: true
                %br
                %h2.label 商品の説明
                %span.must_check 必須
                .goods_form-explain-text
                  =f.text_area :detail, placeholder:"商品の説明(必須1,000文字以内) (色、素材、重さ、定価、注意点など) 例：2010年頃に１万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",class:"goods_form-explain-area", required: true

              .goods_form-detail.clearfix
                %h3.goods_form-detail-title 商品の詳細
                .goods_form-detail-div
                  .goods_form-detail-category
                    %h2.label カテゴリー
                    %span.must_check 必須
                    .goods_form-detail-category-list
                      = f.select :parent_name, @category_parent_array, {selected:@product.category.parent.parent.name}, {class: 'listing-select-wrapper__box--select', id:  'parent_category', name: ''}
                    .goods_form-detail-category-list#children_wrapper
                      = f.select :child_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "---", selected: @product.category.parent.id}),{}, {class: 'listing-select-wrapper__box--select', id:  'child_category', name: ''}
                    .goods_form-detail-category-list#grandchildren_wrapper
                      = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "---", selected: @product.category.id}),{},{class: 'listing-select-wrapper__box--select', id:  'grandchild_category', name: 'product[category_id]'}
                  %br
                  .goods_form-detail-bland
                    %h2.label ブランド
                    %span.must_check 任意
                    %br
                    = f.select :brand_id, [["シャネル",1],["ナイキ",2],["ユニクロ",3],["GU",4]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list'}
                  %br
                  .goods_form-detail-status
                    %h2.label 商品の状態
                    %span.must_check 必須
                    %br
                    = f.select :condition, [["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れ無し","目立った傷や汚れ無し"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}

              .goods_form-fee.clearfix
                %h3.goods_form_fee-title 配送について
                .goods_form-fee-div
                  .goods_form-fee-price
                    %h2.label 配送料の負担
                    %span.must_check 必須
                    %br
                    = f.select :fee_payer, [["送料込み(出品者負担)", "出品者負担"],["着払い(購入者負担)", "購入者負担"]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}
                  %br
                  .goods_form-fee-adress
                    %h2.label 発送元の地域
                    %span.must_check 必須
                    %br
                    = f.collection_select :prefecture_id,Prefecture.all, :id, :name , { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}
                  %br
                  .goods_form-fee-blank
                    %h2.label 発送までの日数
                    %span.must_check 必須
                    %br
                    = f.select :delivery, [["1~2日で発送","1~2日で発送"],["2~3日で発送","2~3日で発送"],["4~7日で発送","4~7日で発送"]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}

              .goods_form-price.clearfix
                %h3.goods_form-price-number 販売価格(300~9,999,999)
                %ul.goods_form-price-list
                  %li.goods_form-price-list-list1
                    .goods_form-price-list-list1-title
                      %label.goods_form-price-list-list1-title-label
                        %h2.label 価格
                        %span.must_check 必須
                    .goods_form-price-list-list1-input
                      ¥
                      .goods_form-price-list-list1-input-box
                        =f.text_field :price, placeholder:"例) 300",class:"goods_form-price-list-list1-input-box-field",required: true;
              .goods_form-send
                .goods_form-send-term
                  %p
                    禁止されている出品、行為を必ずご確認ください。
                  %p
                    またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
                  %p
                    また、出品をもちまして加盟店規約に同意したことになります。

                =f.submit value:"完了する",class:"edit_send-btn"
                %br
                = link_to "戻る", root_path, class:'goods_form-send-graybtn'
    .footer
      = render partial:"devise/footer"

app/views/products/index_Top_page.html.haml
.wrapper
  .top-page-header
    = render "products/shared/header"
  .main-content
    = render "products/index_Top_page/main-title"
    = render "products/index_Top_page/top-introduction"
    = render "products/index_Top_page/middle-links"
    = render "products/index_Top_page/characteristic"
  .pick-ups
    .pick-up__category
      = render "products/index_Top_page/pick-up-category"
    .pick-up__brand
      = render "products/index_Top_page/pick-up-brand"
  .exhibition
    = render "products/shared/exhibition-btn"

  = render "products/shared/footer"

app/views/products/index_all.html.haml
.header
  = render 'products/shared/header'
.index-all
  .index__category
    .index__category__title
      カテゴリー
    .category__name__list
      = link_to "", class: "category__name" do
        メンズ
      = link_to "", class: "category__name" do
        レディース
      = link_to "", class: "category__name" do
        ベビー・キッズ
      = link_to "", class: "category__name" do
        インテリア
      = link_to "", class: "category__name" do
        本


    .products-list
      .products-list__name
        アイテム一覧
      %ul.products
        = render partial: 'products/shared/product', collection: @products

.footer
  = render 'products/shared/footer'

app/views/products/new.html.haml
.sign_up
  = render partial:"devise/header" 
  - breadcrumb :product_new
  = breadcrumbs pretext: "",separator: " &rsaquo; " 
  %main.shipping_main
    %section.shipping_main-container
      .goods_main-inner
        .goods_main-header
          %h2.goods_main-header-text
            商品の情報を入力
        = form_with model: @product,local: true do|f|
          .goods_info
            %section.l-shipping_goods_info
            .goods_form

              .goods_form-image.clearfix
                %h2.goods_form_image-title
                  %h2.label 出品画像
                  %span.must_check 必須
                %br
                %p.goods_form-image-text 最大１０枚までアップロードできます
                .goods_field
                  .goods_field-box
                    .goods_field-box-inner
                      =f.fields_for :images,@product.images.build do |i|
                        .goods_field-box-inner-html#js_html
                          =i.file_field :images,multipart: true,class: "goods_field-box-inner-html-file",id:"image_0",accept: "image/*",data: {image:i.index}
                          .goods_field-box-inner-html_text
                            = image_tag(image_path("material/icon/icon_camera.png"), width:"40")
                            %p クリックしてファイルをアップロード


              .goods_form-explain.clearfix
                %h2.label 商品名
                %span.must_check 必須
                .goods_form-explain-title
                  =f.text_field :name, placeholder:"商品名（必須40文字まで)",class:"goods_form-explain-field", required: true
                %br
                %h2.label 商品の説明
                %span.must_check 必須
                .goods_form-explain-text
                  =f.text_area :detail, placeholder:"商品の説明(必須1,000文字以内) (色、素材、重さ、定価、注意点など) 例：2010年頃に１万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",class:"goods_form-explain-area", required: true

              .goods_form-detail.clearfix
                %h3.goods_form-detail-title 商品の詳細
                .goods_form-detail-div
                  .goods_form-detail-category
                    %h2.label カテゴリー
                    %span.must_check 必須
                    .goods_form-detail-category-list
                      = f.select :category_id, @category_parent_array, {prompt:"---"}, {class: 'listing-select-wrapper__box--select', id:  'parent_category', name: ''}
                  %br
                  .goods_form-detail-bland
                    %h2.label ブランド
                    %span.must_check 任意
                    %br
                    = f.select :brand_id, [["シャネル",1],["ナイキ",2],["ユニクロ",3],["GU",4]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list'}
                  %br
                  .goods_form-detail-status
                    %h2.label 商品の状態
                    %span.must_check 必須
                    %br
                    = f.select :condition, [["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れ無し","目立った傷や汚れ無し"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}

              .goods_form-fee.clearfix
                %h3.goods_form_fee-title 配送について
                .goods_form-fee-div
                  .goods_form-fee-price
                    %h2.label 配送料の負担
                    %span.must_check 必須
                    %br
                    = f.select :fee_payer, [["送料込み(出品者負担)", "出品者負担"],["着払い(購入者負担)", "購入者負担"]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}
                  %br
                  .goods_form-fee-adress
                    %h2.label 発送元の地域
                    %span.must_check 必須
                    %br
                    = f.collection_select :prefecture_id,Prefecture.all, :id, :name , { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}
                  %br
                  .goods_form-fee-blank
                    %h2.label 発送までの日数
                    %span.must_check 必須
                    %br
                    = f.select :delivery, [["1~2日で発送","1~2日で発送"],["2~3日で発送","2~3日で発送"],["4~7日で発送","4~7日で発送"]], { include_blank: "選択して下さい"}, { class: 'goods_form-fee-price-list', required: true}

              .goods_form-price.clearfix
                %h3.goods_form-price-number 販売価格(300~9,999,999)
                %ul.goods_form-price-list
                  %li.goods_form-price-list-list1
                    .goods_form-price-list-list1-title
                      %label.goods_form-price-list-list1-title-label
                        %h2.label 価格
                        %span.must_check 必須
                    .goods_form-price-list-list1-input
                      ¥
                      .goods_form-price-list-list1-input-box
                        =f.text_field :price, placeholder:"例) 300",class:"goods_form-price-list-list1-input-box-field",required: true;
              .goods_form-send
                .goods_form-send-term
                  %p
                    禁止されている出品、行為を必ずご確認ください。
                  %p
                    またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
                  %p
                    また、出品をもちまして加盟店規約に同意したことになります。

                =f.submit value:"出品する",class:"goods_form-send-redbtn"
                %br
                = link_to "戻る", root_path, class:'goods_form-send-graybtn'
    .footer
      = render partial:"devise/footer"

app/views/products/search.html.haml
.header
  = render 'products/shared/header'
.side-bar
  = render 'products/searches/form-bar'

.index-all
  .index__category
    .products-list
      .products-list__name
        検索結果
      - if @products.length == 0
        .search_nothing  
          条件に一致する商品はありません
      - else
        %ul.products
          - @products.each do |product|
            = render partial: 'products/shared/product', locals: { product: product }

.footer
  = render 'products/shared/footer'

app/views/products/show.html.haml
.top-page-header
  = render "products/shared/header"
  - breadcrumb :product_show
  = breadcrumbs pretext: "",separator: " &rsaquo; "
.goods__details
  .goods__details--title 
    = @product.name
  .goods__details--summary
    = "#{@product.name}は#{@product.user.nickname}さんから出品されました。"
  .goods__details--mains
    .goods__details--mains--images
      .active-image
        = image_tag @image.first.images.url, class: "active-image"
      .each-images
        - @image.each do |img|
          = image_tag img.images.url, class: "each-image"

    .goods__details--mains--table
      %table{ border: "1", bordercolor: "#cccccc"}
        %tr 
          %td.left-data{height: "40"} 出品者
          %td.right-data 
            = @product.user.nickname
        %tr  
          %td.left-data{height: "40"} カテゴリー
          %td.right-data 
            = "#{@product.category.parent.parent.name}"
            %br/
            = ">#{@product.category.parent.name}"
            %br/
            = ">#{@product.category.name}"
        %tr
          %td.left-data{height: "40px"} ブランド
          %td.right-data
            - if @product.brand.present?
              = @product.brand.name
            - else
              未登録
        %tr
          %td.left-data{height: "40px"}  商品の状態
          %td.right-data 
            = @product.condition
        %tr
          %td.left-data{height: "40px"}  配送料の負担
          %td.right-data 送料込み（出品者負担）
        %tr
          %td.left-data{height: "40px"} 配送の方法
          %td.right-data 郵便局
        %tr
          %td.left-data{height: "40px"}  配送元地域
          %td.right-data  
            = @product.prefecture.name
        %tr
          %td.left-data{height: "40px"}  発送日の目安
          %td.right-data 
            = "#{@product.delivery}日"

  .goods__details--price
    %span 
      = "#{@product.price}円" 
    (税込)送料込み

  - if user_signed_in? && current_user.id == @product.user.id
    - if @product.purchase.present?
      .goods__details--option
        .btn2
          = link_to '出品の取り消し', product_path(@product.id), method: :delete, class: "btn2"
    - else
      .goods__details--option
        .btn1
          = link_to "商品の編集", edit_product_path(@product.id), class: "btn1"
        .btn2
          = link_to '出品の取り消し', product_path(@product.id), method: :delete, class: "btn2"
  - else
    - if @product.purchase.present?
      .goods__details--buybtn--non
        .non-btn
          SOLD OUT
    - else
      .goods__details--buybtn
        = link_to "購入画面にすすむ", buy_product_purchases_path(product_id: @product.id), class: "btn"
      
  .goods__details--comment
    = @product.detail
  .goods__details--else
    %button.good-btn
      = render partial: 'likes/like', locals: {product: @product, likes: @likes}
    %button.report-btn
      不適切な商品の報告
    = link_to '#', class: "safety-rule" do
      %i.fas.fa-lock.lock-icon 
      = "安心・安全への取り組み"

.page
  .around__goods
    - if @product.previous.present?
      = link_to "＜ #{@product.previous.name}", @product.previous ,class: "before-goods"
    - if @product.next.present?
      .back-goods
      = link_to "#{@product.next.name} ＞", @product.next ,class: "after-goods"

  .icon__area
    .messages
      .message
        - @comments.each do |c|
          .message__name
            = c.user.nickname
          .message__text
            = c.body
            .message__text--date
              = c.created_at.to_s(:datetime_jp)
    .comment
      - if current_user
        = form_with model: [@product, @comment], local: true, class: "forms" do |form|
          = form.text_area :body, class: "comment-form", size: "70x3", placeholder: "コメントを入力してください"
          = form.submit "コメントする", class: "submit-form"
      - else
        .comment__message
          = link_to "ログインしてコメントをしてみましょう", user_session_path, class: "comment-link"

= render "products/shared/footer"